server:
  port: 8080
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/database_system?characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: src.mes_server.pojo,;src.mes_server.dto
